easy_admin:
    entities:
        # List the entity class name you want to manage
        Customer:
            class: App\Entity\Customer
            controller: App\Controller\Admin\CustomerController
            form:
                fields:
                    - name
                    - email
                    - phone
                    - { property: 'attributes', type: 'collection', type_options: {entry_type: 'App\Form\CustomerAttributeType', allow_delete: false, allow_add: false}}
        Attribute:
            class: App\Entity\Attribute
        User:
            class: App\Entity\User