easy_admin:
    entities:
        # List the entity class name you want to manage
        Customer:
            class: App\Entity\Customer
            controller: App\Controller\Admin\CustomerController
        Attribute:
            class: App\Entity\Attribute